name: Build with Nix Flake

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Get flake input hash
      id: flake-hash
      run: echo "hash=$(nix flake metadata --json | jq -r .locked.narHash)" >> "$GITHUB_OUTPUT"

    - name: Cache flake build
      uses: actions/cache@v4
      with:
        path: /nix/store
        key: nix-flake-${{ steps.flake-hash.outputs.hash }}
        restore-keys: |
          nix-flake-

    - name: Build WASM via Nix flake
      run: |
        nix develop --command make REPOSITORY=$GITHUB_REPOSITORY push-cluster
